### ISSUE TITLE
Exclude route="pipeline"

### ISSUE THREAD

**Issue by kudlav** [Jungle-Bus/unroll#18]
Pipelines are not designed for public transport:
https://jungle-bus.github.io/unroll/route.html?line=11084860
https://www.openstreetmap.org/relation/11084860

**Comment by nlehuby** [comment]
I don't think it's a big deal if the `route.html` page displays something for pipeline relations. I don't see much point in adding code to restrict this usage, even if it doesn't make sense in Unroll.

On the other hand, it would be problematic if pipelines would go up in the search (the home page). Is this the case?

**Comment by kudlav** [comment]
Yes, it's displayed in search result, see:

![Screenshot_20210306-113122_Firefox Beta](https://user-images.githubusercontent.com/11516259/110203634-8e5f1e00-7e6f-11eb-8bd9-89e9205e2f7d.jpg)

**Comment by kudlav** [comment]
I have found the issue of empty title, it had the following tags:
type = route_master  
route = pipeline  

instead of route_master = pipeline

But still it's useless to be listed in public transport routes

![Screenshot_20210306-234827_Firefox Beta](https://user-images.githubusercontent.com/11516259/110222955-9dc58200-7ed6-11eb-99bd-dfd4fad90681.png)

**Comment by nlehuby** [comment]
I've filtered out `pipeline` route_master and a few other non relevant ones on the search page results. Thanks again for the issue :+1: 
But I choose to keep the empty ones: route_master is mostly used for public_transport anyway, so I think it is more likely to be a public transport route_master with a mistake (`route`=`some pt mode` instead of `route_master`=`some pt mode`) than a unrelated relations that we don't want to display.

**Comment by kudlav** [comment]
Hi, I totally agree, it makes sense to diplay empty ones, as it is problem with data itself not this tool. And thanks to this behaviour I was able to find out this mistake and correct the tag.

Thanks for the work you've done and for this tool!
